### PR TITLE
Remove docker publish from CI

### PR DESCRIPTION
**Pull request by jasonhealy**

### CODE REVIEW

**Review by mirceanis — COMMENTED** [review]
why the removal?

**Comment by jasonhealy** [comment]
That's part of the main DAF release. When a new DAF core is release we create a docker image of it and publish it. Doesn't make sense publishing it from here

**Comment by mirceanis** [comment]
Right, that's why I'm asking.
The cli is in this repo so it makes more sense to keep the docker publishing here and remove it from there (if it hasn't already been removed from the beta branch)

**Comment by mirceanis** [comment]
We're putting this repo on hold for now so I'm closing this

**Pull request closed without merging**
